//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRoshanTailor
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMeasurement
    {
        public int MId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DateOfOrder { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public string BillingDetails { get; set; }
        public string MeasureMentDetails { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
